- package-lock.json
- package.json
- src/App.jsx
axios, react-route-dom, styled-components, redux-toolkit ,react-jwt 설치
> 기본 라이브러리 설치

- package-lock.json
- package.json
**PR** : react hook form에서 자료형 관리를 위해서 하단 module 설치 
- **Yup**, object schema vaildation  
- 변경 파일:
```
package.json
package-lock.json
```
> module Yup 설치

- package-lock.json
- package.json
- src/components/recipeMain/RecipeBody.jsx
- src/components/recipeMain/RecipeList.jsx
- src/pages/Recipe.jsx
<b>PR</b> : main page 및 개인페이지에서 효과적인 리스트확인을 위해서 하단 module 설치
- react-slick, slick-carousel
- 변경파일:
```
package.json
package-lock.json
```
> create react-slick 캐러셀 적용

- src/components/recipeCreate/RecipeCreateForm.jsx
- src/components/recipeDetail/RecipeDesc.jsx
- src/components/recipeDetail/RecipeTitle.jsx
- src/components/recipeDetail/element/RecipeDescBody.jsx
- src/components/recipeDetail/element/RecipeTitle.jsx
- src/pages/RecipeDetail.jsx
**PR**: 레시피 디테일 초안 페이지에서 내용 추가+컴포넌트 구조 리팩토링 하였습니다.
```
src\pages\RecipeDetail.jsx
src\components\recipeDetail\RecipeDesc.jsx
src\components\recipeDetail\element\RecipeDescBody.jsx
src\components\recipeDetail\element\RecipeTitle.jsx
src\components\recipeCreate\RecipeCreateForm.jsx
```
> update 레시피 디테일 페이지 #21

- src/components/recipeCreate/subpages/RecipeCupSize.jsx
- src/components/recipeCreate/subpages/RecipeIngredientList.jsx
- src/components/recipeDetail/IngredientsContainer.jsx
- src/components/recipeDetail/element/Ingredient.jsx
- src/components/recipeDetail/element/IsIcedIcon.jsx
- src/util/recipeSetDataType.js
**PR**: refactor 레시피 디테일 페이지, 작성 페이지, 코드 리뷰 1차 반영  
todo: 9월 1일 코드리뷰 내용 이슈로 정리할 것!
```
src\util\recipeSetDataType.js
src\components\recipeCreate\subpages\RecipeCupSize.jsx
src\components\recipeCreate\subpages\RecipeIngredientList.jsx
src\components\recipeDetail\IngredientsContainer.jsx
src\components\recipeDetail\element\Ingredient.jsx
src\components\recipeDetail\element\IsIcedIcon.jsx
```
---
> refactor 레시피 디테일 페이지, 작성 페이지, 코드 리뷰 1차 반영

- package-lock.json
- src/App.jsx
- src/common/Footer.jsx
- src/common/Layout.jsx
- src/components/recipeMain/RecipeBody.jsx
- src/components/recipeMain/RecipeListContainer.jsx
- src/components/recipeMypage/MypageBody.jsx
- src/pages/Mypage.jsx
- src/pages/Recipe.jsx
- src/pages/RegisterEdit.jsx
- src/partial/Footer.jsx
- src/partial/Header.jsx
- src/shared/Router.jsx
<b>PR</b>: refactor 레이아웃, 마이페이지 반영
```
src\common\Layout.jsx
src\pages\Mypage.jsx
src\partial\Footer.jsx
src\partial\Header.jsx
```
> refactor 레시피 레이아웃, 마이페이지 반영

- src/components/recipeCreate/subpages/RecipeIsIced.jsx
- src/components/recipeDetail/IngredientsContainer.jsx
- src/components/recipeDetail/element/IsIcedIcon.jsx
- src/components/recipeDetail/element/RecipeDescBody.jsx
- src/components/recipeDetail/element/RecipeTitle.jsx
- src/pages/RecipeCreate.jsx
- src/pages/RecipeDetail.jsx
- src/partial/Navigation.jsx
**PR**:  
1. update 레시피 디테일 페이지 CSS 수정하였습니다.
2. src\partial\Navigation.jsx 컴포넌트를 생성하였습니다.
```
src\components\recipeCreate\subpages\RecipeIsIced.jsx
src\components\recipeDetail\IngredientsContainer.jsx
src\components\recipeDetail\element\IsIcedIcon.jsx
src\components\recipeDetail\element\RecipeDescBody.jsx
src\components\recipeDetail\element\RecipeTitle.jsx
src\pages\RecipeCreate.jsx
src\pages\RecipeDetail.jsx
src\partial\Navigation.jsx
```
> update 레시피 디테일 페이지 CSS update

- src/components/register/Email.jsx
- src/components/register/Image.jsx
- src/components/register/Nickname.jsx
- src/pages/Register.jsx
**PR** : style 회원가입 css 추가
`src\pages\Register.jsx`
`src\components\register\Email.jsx`
`src\components\register\Password.jsx`
`src\components\register\Image.jsx`
`src\components\register\Nickname.jsx`
> style회원가입 css 추가

- src/pages/Login.jsx
- src/pages/Register.jsx
**PR** : 이미지없을 때 버튼이 눌려서 다음 페이지 이동 오류 -> 수정
`src\pages\Register.jsx`
> 이미지없을 때 버튼 눌림 수정

- src/components/profileEdit/ProfileEditBody.jsx
- src/components/recipeCreate/subpages/RecipeIngredientList.jsx
- src/components/recipeDetail/IngredientsContainer.jsx
- src/components/recipeDetail/RecipeDesc.jsx
- src/components/recipeDetail/element/RecipeDescBody.jsx
- src/pages/ProfileEdit.jsx
- src/pages/RecipeCreate.jsx
이후 마이페이지 작업할 예정입니다.
**PR** : 
프로필 페이지: 누락된 props 추가(watch)
레시피 상세 페이지: 콘솔에 뜨는 key에러 수정,
레시피 작성 페이지 : 문구 안 떠서 조건부랜더링 수정
```
src\pages\ProfileEdit.jsx
src\pages\RecipeCreate.jsx
src\components\profileEdit\ProfileEditBody.jsx
src\components\recipeCreate\subpages\RecipeIngredientList.jsx
src\components\recipeDetail\IngredientsContainer.jsx
src\components\recipeDetail\RecipeDesc.jsx
src\components\recipeDetail\element\RecipeDescBody.jsx
```
> 자잘한 버그 수정: props누락, 재료목록key, 조건부랜더링 수정

- src/components/recipeMypage/MypageBody.jsx
- src/components/recipeMypage/MypageMyInfo.jsx
- src/components/recipeMypage/MypageRecipeLikeList.jsx
- src/components/recipeMypage/MypageRecipeMyList.jsx
- src/components/recipeMypage/element/Ingredient.jsx
- src/components/recipeMypage/element/IngredientList.jsx
- src/components/recipeMypage/element/RecipeListToggle.jsx
- src/components/recipeMypage/element/RecipeSilder.jsx
- src/pages/Mypage.jsx
**PR** : 마이페이지 뷰 + 전체 기능 추가
```
src\pages\Mypage.jsx
src\components\recipeMypage\MypageMyInfo.jsx
src\components\recipeMypage\MypageRecipeLikeList.jsx
src\components\recipeMypage\MypageRecipeMyList.jsx
src\components\recipeMypage\element\IngredientList.jsx
src\components\recipeMypage\element\Ingredient.jsx
src\components\recipeMypage\element\RecipeListToggle.jsx
src\components\recipeMypage\element\RecipeSilder.jsx
```
```
Mypage
├─MypageMyInfo
├─MypageRecipeLikeList
│  └─RecipeListToggle
│  └─RecipeSilder
│       └─IngredientList
│            └─Ingredient
└─MypageRecipeMyList
└─RecipeListToggle
└─RecipeSilder
└─IngredientList
└─Ingredient
```
> Feature 마이페이지 뷰 완성

- package-lock.json
- package.json
- vite.config.js
**PR** : Vite-plugin-svgr 설치
- react에서 SVG 파일을 컴포넌트로 불러올 수 있는 lib입니다.
- https://www.npmjs.com/package/vite-plugin-svgr
```
package-lock.json
package.json
vite.config.js
```
> Module vite-plugin-svgr 설치 완료 #52

- src/server/api.js
- src/server/auth.service.js
- src/server/token.service.js
- 이슈 해결: #56
- 수정 파일
```
src\server\api.js
src\server\auth.service.js
src\server\token.service.js
```
- 사용법 예시
```
import customAxios from '../server/api' // api.js를 import
...
방법A
const response = await customAxios("application/json").get(`/recipes/${recipeId}`) // content-type을 인수로 전달 + get메소드
...
방법B
let apiJson = customAxios("application/json")  // content-type을 인수로 전달, 변수에 함수 지정
const response = await apiJson.get(`/recipes/${recipeId}`)  // get메소드
```
> Create : Axios intercepter #56

- src/components/recipeComment/CommentBody.jsx
- src/components/recipeComment/CommentDelete.jsx
- src/components/recipeComment/CommentEdit.jsx
- src/components/recipeComment/CommentInput.jsx
- src/components/recipeComment/CommentOption.jsx
- src/pages/Comments.jsx
- src/partial/Navigation.jsx
**PR** : 댓글 CRUD 기능, 사진업로드 기능추가(사진 수정 및 삭제 진행중)
```
src\pages\Comments.jsx
src\components\recipeComment\CommentInput.jsx
src\components\recipeComment\CommentEdit.jsx
src\components\recipeComment\CommentDelete.jsx
src\components\recipeComment\CommentOption.jsx
```
> Create 댓글 CRUD기능과 사진업로드 기능 추가

- src/components/recipeCreate/RecipeCreateForm.jsx
- src/components/recipeDetail/IngredientsContainer.jsx
- src/components/recipeDetail/RecipeDesc.jsx
- src/pages/RecipeCreate.jsx
- src/pages/RecipeDetail.jsx
- src/server/api.js
**PR** : 레시피 작성, 레시피 상세 페이지 API확인 완료했습니다.
```
src\server\api.js
src\pages\RecipeDetail.jsx
src\pages\RecipeCreate.jsx
src\components\recipeDetail\RecipeDesc.jsx
src\components\recipeDetail\IngredientsContainer.jsx
src\components\recipeCreate\RecipeCreateForm.jsx
```
> Feature 레시피 작성, 레시피 상세 페이지 API연결

- .gitignore
- src/components/recipeComment/CommentInput.jsx
- src/components/recipeMain/AllRecipeList.jsx
- src/components/recipeMain/AllRecipeListContainer.jsx
- src/components/recipeMain/RecipeBody.jsx
- src/pages/Recipe.jsx
**PR** : 
- 코멘트 미리보기 삭제 기능 추가, 무한스크롤 mock api활용하여 기능확인
```
cupicks-fe\src\components\recipeComment\CommentInput.jsx
```
> Create 미리보기 삭제 기능 추가, 무한스크롤 기능확인

- src/components/recipeMain/AllRecipeListContainer.jsx
- src/components/recipeMain/RecipeListContainer.jsx
- src/pages/Landing.jsx
- src/pages/NotFound.jsx
- src/partial/Footer.jsx
- src/partial/Header.jsx
- src/shared/Router.jsx
> Update SVG 경로 수정

- src/Main.jsx
- src/components/recipeMain/AllRecipeList.jsx
- src/components/recipeMain/AllRecipeListContainer.jsx
- src/components/recipeMain/RecipeBody.jsx
**PR** : 
- 무한스크롤 페이지 axios연결 및 스피너 생성
```
src\components\recipeMain\RecipeBody.jsx
src\components\recipeMain\AllRecipeList.jsx
src\components\recipeMain\AllRecipeListContainer.jsx
```
> Create 무한스크롤 axios연결 및 스피너 생성

- src/components/register/Email.jsx
- src/components/resetPassword/CheckEmail.jsx
- src/pages/Login.jsx
- src/pages/Register.jsx
- src/pages/ResetPassword.jsx
- src/shared/Router.jsx
**PR** : 
- 비밀번호 찾기 페이지 추가
```
src\components\resetPassword\CheckEmail.jsx
```
> 비밀번호 찾기 페이지 추가

- index.html
- src/Main.jsx
- src/common/GlobalStyle.jsx
- src/components/elements/button/NavButtonGoBack.jsx
- src/components/elements/button/NavButtonNextLevel.jsx
- src/components/elements/button/NavButtonNextSubLevel.jsx
- src/components/recipeCreate/RecipeCreateNavigation.jsx
- src/components/recipeCreate/RecipeCreateWrap.jsx
- src/components/recipeCreate/RecipeFormContainer.jsx
- src/components/recipeCreate/RecipeVisualContainer.jsx
- src/components/recipeCreate/element/ProgressIconBar.jsx
- src/components/recipeCreate/element/RecipeCreateIngredient.jsx
- src/components/recipeCreate/element/RecipeCreateModal.jsx
- src/components/recipeCreate/element/RecipeIngredient.jsx
- src/components/recipeCreate/element/RecipeIngredientColorList.jsx
- src/components/recipeCreate/element/RecipeIngredientColorLists.jsx
- src/components/recipeCreate/element/RecipeIngredientNumber.jsx
- src/components/recipeCreate/subpages/RecipeCupSize.jsx
- src/components/recipeCreate/subpages/RecipeIngredientButtonContainer.jsx
- src/components/recipeCreate/subpages/RecipeIngredientForm.jsx
- src/components/recipeCreate/subpages/RecipeIsIced.jsx
- src/components/recipeCreate/subpages/RecipeTextValue.jsx
- src/pages/RecipeCreate.jsx
- src/util/windowInnerHeightSet.js
**PR** : 
- 레시피 작성 페이지 UI 적용 및 리팩토링 및 버그 수정 
- 변경파일 리스트
> Update : 레시피 작성 페이지 UI 적용 및 리팩토링 및 버그 수정 #61

- src/components/register/Email.jsx
**PR** : 
- 이메일 에러메시지 alert 추가
```
src\components\register\Email.jsx
```
> 이메일 알림창 띄우기 수정

- src/components/elements/modal/ConfirmBox.jsx
- src/components/elements/modal/ToastMessage.jsx
- src/components/recipeCreate/RecipeCreateNavigation.jsx
- src/error.html
- src/pages/RecipeCreate.jsx
**PR** : 
- 모달 컴포넌트 제작
```
src\components\elements\modal\ConfirmBox.jsx
src\components\elements\modal\ToastMessage.jsx
src\components\recipeCreate\RecipeCreateNavigation.jsx
src\pages\RecipeCreate.jsx
src\error.html
```
> Feature 모달 컴포넌트 제작

- src/components/elements/modal/ConfirmBox.jsx
- src/components/elements/modal/ToastMessage.jsx
- src/components/recipeCreate/RecipeCreateNavigation.jsx
- src/pages/Landing.jsx
- src/pages/Login.jsx
- src/pages/NotFound.jsx
**PR** : 
- #82 이슈 관련 ComfirmBox 컴포넌트 버그 수정
- 모달 배경 클릭
- 모달 fadeOut 속도
- 모달 위치
> Bugfix: #82 이슈 관련 ComfirmBox 컴포넌트 버그 수정

- src/pages/Login.jsx
**PR** : 
- 로그인 페이지 CSS
```
src\pages\Login.jsx
```
> Upate 로그인 페이지 CSS #85

- src/pages/Login.jsx
**PR** : 
- 로그인 페이지 버튼 수정 및 hover 수정
- 원석님과 대화 후, CSS 빠트린 부분 수정하였습니다.
> Style 로그인 페이지 버튼 수정 및 hover 수정

- src/components/recipeMain/AllRecipeList.jsx
- src/components/recipeMain/AllRecipeListContainer.jsx
- src/components/recipeMain/AllRecipeListIngredient.jsx
- src/components/recipeMain/RecipeBody.jsx
- src/pages/Recipe.jsx
- src/shared/Router.jsx
**PR** : 
- Style 레시피 메인(커뮤니티) 페이지 1차 CSS 완료
> Style 레시피 메인(커뮤니티) 페이지 1차 CSS 완료

- src/components/elements/modal/ConfirmBox.jsx
- src/components/register/Email.jsx
- src/pages/Register.jsx
- vite.config.js
**PR** : 
- 회원가입 페이지 뒤로가기 버튼 모달 창 추가
- 이메일 에러메시지 모달 창 추가
```
src\components\register\Email.jsx
```
> 회원가입(이메일,뒤로가기) 모달창 추가

- src/components/recipeCreate/RecipeCreateWrap.jsx
- src/components/recipeDetail/element/RecipeTitle.jsx
- src/components/recipeMain/AllRecipeList.jsx
- src/components/recipeMypage/MypageMyInfo.jsx
- src/components/recipeMypage/MypageRecipeMyList.jsx
- src/components/recipeMypage/element/Ingredient.jsx
- src/components/recipeMypage/element/IngredientList.jsx
- src/components/recipeMypage/element/RecipeListToggle.jsx
- src/components/recipeMypage/element/RecipeSilder.jsx
- src/pages/Mypage.jsx
- src/pages/ProfileEdit.jsx
- src/server/token.service.js
- src/shared/Router.jsx
**PR** : 
- 커뮤니티 페이지, 마이페이지 수정사항 #95 #88
```
변경파일 리스트
```
> Update 커뮤니티 페이지, 마이페이지 수정사항 #95 #88

- src/components/profileEdit/ProfileEditBody.jsx
- src/components/profileEdit/ProfileEditHeader.jsx
- src/components/recipeMain/AllRecipeList.jsx
- src/components/recipeMain/AllRecipeListContainer.jsx
- src/components/recipeMypage/MypageMyInfo.jsx
- src/pages/Mypage.jsx
- src/pages/ProfileEdit.jsx
- src/partial/Footer.jsx
**PR** : 
- 마이페이지 API연결, 로그아웃 메뉴, CSS 수정
- 프로필 수정 페이지 API연결, CSS 수정
> Update 마이페이지, 프로필 수정 페이지 #95 #98

- src/common/GlobalStyle.jsx
- src/components/profileEdit/ProfileEditBody.jsx
- src/components/profileEdit/ProfileEditHeader.jsx
- src/pages/ProfileEdit.jsx
- src/partial/Navigation.jsx
- src/server/api.js
> Update 프로필 작성 페이지 수정중

- src/common/GlobalStyle.jsx
- src/components/recipeDetail/IngredientsContainer.jsx
- src/components/recipeDetail/RecipeDesc.jsx
- src/components/recipeDetail/element/Ingredient.jsx
- src/components/recipeDetail/element/IsIcedIcon.jsx
- src/components/recipeDetail/element/RecipeDescBody.jsx
- src/components/recipeDetail/element/RecipeTitle.jsx
- src/components/recipeMain/AllRecipeListContainer.jsx
- src/pages/RecipeDetail.jsx
- src/partial/Navigation.jsx
**PR** : 
- 레시피 상세 페이지 CSS + UI추가 + 로직 정리
> Style 레시피 상세 페이지 CSS + UI추가 + 로직 정리 #107

- src/components/recipeMypage/element/Ingredient.jsx
- src/components/recipeMypage/element/IngredientList.jsx
- src/components/recipeMypage/element/RecipeSilder.jsx
**PR** : 
- 마이페이지 얼음 처리, CSS 수정
> Style 마이페이지 얼음 처리, CSS 수정 #93

- src/common/GlobalStyle.jsx
- src/components/RegisterComplete/CompleteOne.jsx
- src/components/RegisterComplete/CompleteThree.jsx
- src/components/RegisterComplete/CompleteTwo.jsx
- src/components/register/Email.jsx
- src/components/register/Image.jsx
- src/components/register/Password.jsx
- src/components/register/Timer.jsx
- src/pages/Login.jsx
- src/pages/Register.jsx
- src/pages/RegisterComplete.jsx
- src/partial/Navigation.jsx
> Style 회원가입 페이지 CSS 작업

- src/components/profileEdit/ProfileEditBody.jsx
- src/components/recipeMain/AllRecipeList.jsx
- src/components/recipeMypage/MypageMyInfo.jsx
- src/pages/Login.jsx
- src/pages/ProfileEdit.jsx
**PR** : 
- nickname input에 있는 버튼을 눌렀을 때 focus 적용
- password input에 있는 버튼을 눌렀을 때 focus 적용
```
src\pages\ProfileEdit.jsx
src\components\profileEdit\ProfileEditBody.jsx
```
> 닉네임,패스워드 focus 추가

- src/components/elements/button/NavButtonDone.jsx
- src/components/elements/button/NavButtonGoMain.jsx
- src/components/recipeComment/CommentInput.jsx
- src/components/recipeCreate/RecipeCreateNavigation.jsx
- src/components/recipeCreate/RecipeCreateWrap.jsx
- src/components/recipeCreate/RecipeVisualContainer.jsx
- src/components/recipeCreate/element/IsIcedIcon.jsx
- src/components/recipeCreate/subpages/RecipeIngredientConform.jsx
- src/components/recipeMain/AllRecipeList.jsx
- src/components/register/Timer.jsx
- src/pages/Register.jsx
- src/partial/Navigation.jsx
**PR** : 
- CSS 레시피 제작, 회원가입 배포용 수정
> Update CSS 레시피 제작, 회원가입 배포용 수정

- package-lock.json
- package.json
**PR** : 
- Module lib 삭제: sweetalert2, yup
> Module lib 삭제: sweetalert2, yup

- src/components/recipeComment/CommentInput.jsx
- src/components/recipeMain/AllRecipeList.jsx
**PR** : 
- Created required true remove
```
src\components\recipeComment\CommentInput.jsx
```
> Created required true remove 처리

- src/Main.jsx
- src/components/recipeCreate/RecipeCreateWrap.jsx
- src/components/recipeMypage/MypageRecipeMyList.jsx
- src/components/recipeMypage/element/RecipeSilder.jsx
- src/pages/Comments.jsx
- src/pages/ResetPassword.jsx
- src/partial/Navigation.jsx
**PR** : 
- 비밀번호 리셋 페이지 CSS
- 메인페이지 버그 수정
```
src\Main.jsx
src\components\recipeCreate\RecipeCreateWrap.jsx
src\components\recipeMypage\MypageRecipeMyList.jsx
src\components\recipeMypage\element\RecipeSilder.jsx
src\pages\Comments.jsx
src\partial\Navigation.jsx
```
> Style 비밀번호 리셋 페이지 CSS

- .eslintrc.cjs
- .prettierrc.cjs
- src/util/recipeIngrediantColorList.js
**PR** : 
- Eslint 테스트 완료
```jsx
{
"name": "cupicks-fe",
"private": true,
"version": "0.0.0",
"type": "module",
"scripts": {
"dev": "vite",
"build": "vite build",
"preview": "vite preview",
"prepare": "husky install"
},
"dependencies": {
"@hookform/resolvers": "^2.9.7",
"axios": "^0.27.2",
"react": "^18.2.0",
"react-dom": "^18.2.0",
"react-hook-form": "^7.34.2",
"react-intersection-observer": "^9.4.0",
"react-jwt": "^1.1.6",
"react-router-dom": "^6.3.0",
"react-slick": "^0.29.0",
"slick-carousel": "^1.8.1",
"styled-components": "^5.3.5",
"vite-plugin-svgr": "^2.2.1"
},
"devDependencies": {
"@types/react": "^18.0.17",
"@types/react-dom": "^18.0.6",
"@vitejs/plugin-react": "^2.0.1",
"eslint": "^8.23.1",
"eslint-config-airbnb": "^19.0.4",
"eslint-config-prettier": "^8.5.0", …
```
> Module Eslint 테스트 완료

- src/components/elements/modal/ToastMessage.jsx
- src/components/recipeMypage/MypageMyInfo.jsx
- src/pages/Login.jsx
- src/pages/NotFound.jsx
- src/pages/Register.jsx
- src/pages/RegisterComplete.jsx
- src/shared/Router.jsx
**PR** : 
- Router.jsx에서 userLoggedIn 핸들링 > 네비게이션 가드
- 접근할 수 없는 페이지에 직접 접속하지 못하게 함
- Router.jsx에서 모든 페이지의 로그인 상태, 로그인이 필요한 페이지를 구분해서 리디렉션
> Update 로그인 & 토큰 expired 처리 #117

- src/pages/Register.jsx
**PR** : 
- fixComplict register 충돌 2번째
- 21일 오후에 공유 받았던 파일로 덮어씀
```
```
> fixComplict register 충돌, 21일에 공유받은 파일로 덮어씀

- src/pages/Register.jsx
**PR** : 
- complete페이지로 이동 안하는 이유 고침
- signUp말고 sign-up 사용
> Bugfix signUp말고 sign-up 사용

- src/components/elements/modal/ToastMessage.jsx
- src/components/recipeCreate/subpages/RecipeIngredientButtonContainer.jsx
- src/pages/Login.jsx
- src/pages/Recipe.jsx
**PR** :
- 로그인 시, 메시지를 추가하였습니다. 
- #145
> Update 로그인 메시지 추가

- index.html
**PR** : 
- favicon 추가
- og태그 추가
```
index.html
```
> favicon, og태그 추가

- src/components/elements/button/NavButtonDone.jsx
- src/components/elements/button/NavButtonNextLevel.jsx
- src/components/elements/button/NavButtonNextSubLevel.jsx
- src/components/elements/button/NavButtonPrevLevel.jsx
- src/components/elements/button/NavButtonPrevSubLevel.jsx
- src/components/recipeCreate/RecipeCreateNavigation.jsx
- src/components/recipeCreate/RecipeCreateWrap.jsx
- src/components/recipeCreate/subpages/RecipeTextValue.jsx
- src/shared/Router.jsx
- src/util/recipeSetDataType.js
**PR** : 
- 레시피 작성 완료버튼 버그 수정
=> 작성 버튼 작동 안하는 버그
- 레시피 작성 공유 버튼 수정
=> 공유 여부 req에 적용 안되던 버그
- #126
> Bugfix 레시피 제작 페이지 변경사항 #126

- src/components/profileEdit/ProfileEditBody.jsx
- src/components/register/Email.jsx
**PR** : 
- 프로필수정페이지-닉네임 유효성 검사 수정
```
src\components\profileEdit\ProfileEditBody.jsx
```
> 프로필수정페이지-닉네임 유효성 검사 수정

- package-lock.json
- src/components/RegisterComplete/CompleteOne.jsx
- src/components/RegisterComplete/CompleteThree.jsx
- src/components/RegisterComplete/CompleteTwo.jsx
- src/components/recipeDetail/element/RecipeTitle.jsx
- src/components/recipeMain/AllRecipeList.jsx
- src/components/recipeMain/AllRecipeListContainer.jsx
- src/pages/Login.jsx
- src/pages/Register.jsx
- src/pages/RegisterComplete.jsx
- src/partial/Footer.jsx
- src/partial/Header.jsx
**PR** : 
- Style CSS 업데이트, #127
> Style CSS 업데이트, #127

- src/components/register/Email.jsx
- src/components/register/Nickname.jsx
- src/components/register/Password.jsx
- src/components/resetPassword/CheckEmail.jsx
- src/pages/Login.jsx
- src/pages/Register.jsx
- src/pages/ResetPassword.jsx
**PR** : 
- 회원가입 페이지 단계에서 input에 있는 내용 삭제 버튼 추가
- 로그인 페이지 단계에서 input에 있는 내용 삭제 버튼 추가
- 비밀번호 찾기 페이지 단계에서 input에 있는 내용 삭제 버튼 추가
```
src\components\register\Email.jsx
src\components\register\Nickname.jsx
src\components\register\Password.jsx
src\components\resetPassword\CheckEmail.jsx
src\pages\Login.jsx
```
> Update 내용 삭제 버튼 추가

- index.html
- test.js
**PR** : 
- Update OG태그 및 파비콘 마무리
> Update OG태그 및 파비콘 마무리

- src/components/recipeComment/CommentBody.jsx
- src/components/recipeMain/AllRecipeList.jsx
- src/components/recipeMain/AllRecipeListContainer.jsx
- src/partial/Footer.jsx
- src/partial/Navigation.jsx
**PR** : 
- #157
- 비로그인으로 **커뮤니티 페이지**에 접속 후, **마이 페이지**를 누르면 
`로그인이 필요한 페이지입니다`를 출력 후 **로그인 페이지**로 이동
- 비로그인으로 **커뮤니티 페이지**에 접속 후, **레시피 작성 버튼**를 누르면 
`레시피 작성에는 로그인이 필요합니다.`를 출력함
- 비로그인으로 **커뮤니티 페이지**에 접속 후, **좋아요 아이콘**를 누르면
"로그인이 필요한 기능입니다"를 출력함
- 비로그인으로 **커뮤니티 페이지**에 접속 후, **댓글 아이콘**를 누르면
"댓글 페이지"를 출력함
- 비로그인으로 **커뮤니티 페이지**에 접속 후, **레시피 상세 페이지**를 누르면 
**레시피 상세 페이지**를 출력함
- 비로그인으로 **레시피 상세 페이지**에 접속 후, **댓글 페이지**를 누르면
"댓글 페이지"를 출력함
- 비로그인으로 **댓글 페이지**에 접속 후,  댓글 작성 영역에 그림자를 씌우고, 클릭 시 안내 문구를 출력
> Feature 비로그인 기능 추가 #157

- src/components/recipeComment/CommentBody.jsx
- src/components/recipeComment/CommentDelete.jsx
- src/components/recipeComment/CommentEdit.jsx
- src/components/recipeComment/CommentInput.jsx
- src/components/recipeComment/CommentOption.jsx
**PR** :
- 디자인 시안에 맞게 CSS 수정 작업
- ![image](https://user-images.githubusercontent.com/94776135/191866581-675e257a-d76b-4691-9654-27cfe879e207.png)
> Style 댓글 페이지 CSS 업데이트 #123

- index.html
- package-lock.json
- package.json
- src/App.jsx
- src/shared/RouteChangeTracker.jsx
- vite.config.js
**PR** : 
- google analytics라이브러리
- #160
> Module React-ga설치: google analytics라이브러리

- src/components/register/Email.jsx
- src/pages/Register.jsx
**PR** : 
- 회원가입 페이지 버튼 일정한 위치로 수정
```
```
> 회원가입 페이지 버튼 일정한 위치로 수정

- src/pages/Mypage.jsx
- src/pages/ProfileEdit.jsx
- vite.config.js
**PR** : 
- #74 프로필수정페이지 모달 추가
```
src\pages\ProfileEdit.jsx
src\pages\Mypage.jsx
```
> #74 프로필수정페이지 모달 추가

- src/components/recipeDetail/element/RecipeDescBody.jsx
- src/components/recipeEdit/RecipeEditFormContainer.jsx
- src/components/recipeEdit/RecipeEditWrap.jsx
- src/components/recipeEdit/element/RecipeEditIngredientConform.jsx
- src/components/recipeEdit/element/RecipeEditInput.jsx
- src/components/recipeEdit/element/RecipeEditTextarea.jsx
- src/components/recipeEdit/subpages/RecipeEditTextValue.jsx
- src/pages/Recipe.jsx
- src/pages/RecipeDetail.jsx
- src/pages/RecipeEdit.jsx
- src/shared/RouteChangeTracker.jsx
- src/shared/Router.jsx
- vite.config.js
**PR** : 
- 레시피 수정 페이지 추가
- #165
> Feature 레시피 수정 페이지 추가

- src/pages/NotFound.jsx
- src/shared/Router.jsx
**PR** : 
- 전체 높이가 다른 페이지와 다른 점 수정
- 페이지를 바로 메인으로 이동시켜서 불편한 UX 수정
- 1초 후 이동에서, 30초 후 이동으로 변경하였습니다.
- 사용자가 뒤로 가기 버튼을 눌러서, 이전 화면으로 이동할 수 있도록 했습니다.
> bugfix 찾을 수 없는 페이지 관련 버그 수정

- src/components/recipeComment/CommentBody.jsx
- src/components/recipeComment/CommentEdit.jsx
- src/components/recipeComment/CommentInput.jsx
- src/components/recipeComment/CommentOption.jsx
- src/components/recipeDetail/element/RecipeTitle.jsx
- src/components/recipeMain/AllRecipeList.jsx
- src/components/recipeMain/AllRecipeListContainer.jsx
- src/components/recipeMain/RecipeBody.jsx
- src/components/recipeMain/RecipeList.jsx
- src/components/recipeMypage/element/RecipeSilder.jsx
- src/pages/Comments.jsx
**PR** : 
- Create like버튼 활성화 mypage 개선 comment bugfix
> Create like버튼 활성화 mypage 개선 comment bugfix

- src/components/register/Email.jsx
- src/components/register/Image.jsx
- src/pages/Login.jsx
- src/pages/Register.jsx
- src/pages/ResetPassword.jsx
**PR** : 
- 로그인,회원가입, 비밀번호 찾기 페이지 onClick 중복 수정
- 빈 이미지가 되었을 때 기본 이미지로 바뀌지 않는 에러 수정
```
src\pages\Login.jsx
src\components\register\Image.jsx
```
> #171 로그인,회원가입, 비밀번호 찾기 페이지 onClick중복수정 및 이미지 수정

- src/components/register/Image.jsx
**PR** : 
- 이미지의 length 오류 수정
```
src\components\register\Image.jsx
```
> 이미지의 length 오류 수정

- src/components/recipeCreate/subpages/RecipeTextValue.jsx
- src/components/recipeDetail/RecipeDesc.jsx
- src/components/recipeDetail/element/RecipeDescBody.jsx
- src/pages/RecipeDetail.jsx
- src/server/api.js
> Feature 레시피 삭제 버튼 구현

- src/components/recipeDetail/IngredientsContainer.jsx
- src/components/recipeDetail/RecipeDesc.jsx
- src/components/recipeDetail/element/RecipeTitle.jsx
- src/components/recipeMain/AllRecipeListContainer.jsx
- src/pages/RecipeDetail.jsx
**PR** : 
- 상세페이지 좋아요 기능 추가
```
src\components\recipeDetail\element\RecipeTitle.jsx
src\components\recipeDetail\RecipeDesc.jsx
src\pages\RecipeDetail.jsx
```
> 상세페이지 좋아요 기능 추가

- src/components/recipeMypage/MypageRecipeLikeList.jsx
- src/components/recipeMypage/MypageRecipeMyList.jsx
- src/components/recipeMypage/element/Ingredient.jsx
- src/components/recipeMypage/element/RecipeSilder.jsx
- src/components/recipeMypage/element/RecipeTitle.jsx
- src/pages/Mypage.jsx
**PR** : 
- 마이페이지 음료비율 수정, 아이템 50개, 레시피 없을 경우의 수  #180
```
변경파일 리스트
```
> Bugfix 마이페이지 음료비율 수정, 아이템 50개, 레시피 없을 경우의 수  #180

- src/components/RegisterComplete/CompleteOne.jsx
- src/components/RegisterComplete/CompleteThree.jsx
- src/components/RegisterComplete/CompleteTwo.jsx
- src/components/register/Email.jsx
- src/components/register/Image.jsx
- src/components/register/Nickname.jsx
- src/components/register/Password.jsx
- src/pages/Login.jsx
- src/pages/Register.jsx
- src/pages/RegisterComplete.jsx
- src/styles/customElementStyle.js
- src/styles/customFormStyle.js
**PR** : 
- 스타일 컴포넌트 테마: 회원가입 페이지
-
> Update 스타일 컴포넌트 테마: 회원가입 페이지

- src/components/recipeComment/CommentBody.jsx
- src/components/recipeComment/CommentEdit.jsx
- src/components/recipeComment/CommentInput.jsx
- src/components/recipeComment/CommentOption.jsx
**PR** : 
- #74 댓글페이지 alert 대신 모달로 수정
```
src\components\recipeComment\CommentBody.jsx
src\components\recipeComment\CommentEdit.jsx
src\components\recipeComment\CommentInput.jsx
src\components\recipeComment\CommentOption.jsx
```
> #74 댓글페이지 alert 대신 모달로 수정

- src/components/recipeComment/CommentEdit.jsx
**PR** : 
- #180 댓글 수정할 시 input안에 defaultValue 값 적용
```
src\components\recipeComment\CommentEdit.jsx
```
> #180 댓글 수정 defaultValue값 적용

- src/components/recipeMain/AllRecipeListContainer.jsx
**PR** : 
- Bugfix 좋아요 버튼 리랜더링
```
src/components/recipeMain/AllRecipeListContainer.jsx
```
> Bugfix 좋아요 버튼 리랜더링

- src/components/recipeComment/CommentBody.jsx
- src/components/recipeComment/CommentInput.jsx
- src/components/recipeMypage/element/RecipeSilder.jsx
- src/styles/customReset.css
**PR** : 
- 마이페이지 좋아요한 리스트 하단 타이틀 안보이는 부분 수정
- 댓글 페이지 flex-box 수정
- 게시글 줄바꿈 내용 수정
- getvalues 콘솔 에러 지움
> Bugfix 마이페이지, 댓글페이지 CSS 등

- src/App.jsx
- src/common/Layout.jsx
- src/components/recipeComment/CommentBody.jsx
- src/components/recipeComment/CommentDelete.jsx
- src/components/recipeComment/CommentEdit.jsx
- src/components/recipeComment/CommentInput.jsx
- src/components/recipeComment/CommentOption.jsx
- src/components/recipeCreate/RecipeCreateNavigation.jsx
- src/components/recipeCreate/RecipeCreateWrap.jsx
- src/components/recipeCreate/element/RecipeTextarea.jsx
- src/components/recipeDetail/IngredientsContainer.jsx
- src/components/recipeDetail/RecipeDesc.jsx
- src/components/recipeDetail/element/Ingredient.jsx
- src/components/recipeMain/AllRecipeList.jsx
- src/components/recipeMypage/element/RecipeSilder.jsx
- src/pages/Login.jsx
- src/pages/NotFound.jsx
- src/partial/Navigation.jsx
- src/util/windowInnerHeightSet.js
**PR** : 
- 배포 중 발생한 오류 수정, 코멘트, 음료 재료
> Bugfix 배포 중 발생한 오류 수정, 코멘트, 음료 재료

- src/components/recipeComment/CommentBody.jsx
- vite.config.js
**PR** : 
- 이미지 주석 풀고 console drop 주석
> Bugfix 이미지 주석 풀고 console drop 주석

- src/components/register/Email.jsx
- src/components/resetPassword/CheckEmail.jsx
- src/pages/Login.jsx
- src/pages/ResetPassword.jsx
- src/styles/customFormStyle.js
**PR** : 
- Style 비밀번호 리셋 페이지 CSS theme
src\components\resetPassword\CheckEmail.jsx
```
CustomWrapFullVH
└─StForm = styled(CustomForm)
├─RecipeCreateNavigation
│  ├─Navigation (props로 children넘김)
│  │     └─StArrowBack
│  ├─CheckEmail
│  │    ├─ToastMessage
│  │    ├─CustomTitle
│  │    ├─CustomInputBox
│  │    ├─CustomInput
│  │    └─CustomErrorBox
│  └─StButton = styled(CustomButton)
└─ToastMessage
```
> Style 비밀번호 리셋 페이지 CSS theme

- src/components/profileEdit/ProfileEditBody.jsx
- src/components/profileEdit/ProfileEditHeader.jsx
- src/components/recipeComment/CommentEdit.jsx
- src/components/recipeMypage/MypageMyInfo.jsx
- src/components/register/Image.jsx
- src/pages/Mypage.jsx
- src/pages/ProfileEdit.jsx
**PR** : 
- 프로필 수정페이지(이미지, 닉네임 적용)
```
src\pages\ProfileEdit.jsx
src\components\profileEdit\ProfileEditBody.jsx
src\components\profileEdit\ProfileEditHeader.jsx
```
> 프로필 수정페이지(이미지, 닉네임 적용)

- src/pages/Login.jsx
- src/partial/Footer.jsx
- src/partial/Header.jsx
- src/styles/GlobalStyle.jsx
- src/styles/customLayoutStyle.js
- src/styles/theme.js
**PR** : 
- 헤더 푸터 네비게이션 CSS theme
이후 회원가입 쪽 버튼 박스 CSS 꼬인 것 해결할 예정
> Style 헤더 푸터 네비게이션 CSS theme

- src/components/register/Email.jsx
- src/components/register/Image.jsx
- src/components/register/Nickname.jsx
- src/components/register/Password.jsx
- src/pages/Login.jsx
- src/pages/Register.jsx
**PR** : 
- Style 회원가입 페이지 인풋의 아이콘 에러 수정
> Style 회원가입 페이지 인풋의 아이콘 에러 수정

- src/pages/Register.jsx
**PR** : 
- 회원가입 import 빠트린 부분 추가
> Style 회원가입 import 빠트린 부분 추가

- src/components/profileEdit/ProfileEditHeader.jsx
- src/components/recipeComment/CommentBody.jsx
- src/components/recipeMypage/MypageMyInfo.jsx
- src/components/register/Nickname.jsx
- src/partial/Header.jsx
**PR** : 
- 이미지 onError 처리
```
src\components\recipeComment\CommentBody.jsx
src\components\profileEdit\ProfileEditHeader.jsx
src\components\recipeMypage\MypageMyInfo.jsx
```
> 이미지 onError 처리

- src/partial/Header.jsx
**PR** : 
- 헤더 오타 수정
- dis => div
> Bugfix 헤더 오타 수정

- src/App.jsx
- src/common/Layout.jsx
- src/pages/Login.jsx
- src/pages/Recipe.jsx
- src/styles/GlobalStyle.jsx
- src/styles/customElementStyle.js
- src/styles/customFormStyle.js
- src/styles/theme.js
- vite.config.js
**PR** : 
- Style 반응형 CSS 작업, 폰트 및 버튼 및 배경색
> Style 반응형 CSS 작업, 폰트 및 버튼 및 배경색

- src/components/recipeComment/CommentBody.jsx
- src/components/recipeComment/CommentDelete.jsx
- src/components/recipeComment/CommentInput.jsx
- src/components/recipeComment/CommentOption.jsx
**PR** : 
- 댓글 수정, 삭제 에러 수정
```
src\components\recipeComment\CommentBody.jsx
src\components\recipeComment\CommentDelete.jsx
src\components\recipeComment\CommentEdit.jsx
src\components\recipeComment\CommentInput.jsx
src\components\recipeComment\CommentOption.jsx
```
> 댓글 수정, 삭제 에러 수정

- src/components/recipeComment/CommentBody.jsx
**PR** : 
- 비로그인일 때 api 호출 안하도록 수정했습니다.
```
src/components/recipeComment/CommentBody.jsx
```
> Bugfix 댓글 비로그인 콘솔 에러 수정

- src/components/elements/modal/ToastMessage.jsx
- src/components/recipeMain/AllRecipeList.jsx
- src/components/recipeMain/AllRecipeListContainer.jsx
- src/components/recipeMain/RecipeBody.jsx
- src/pages/Login.jsx
- src/pages/Recipe.jsx
- src/pages/Register.jsx
- src/pages/RegisterComplete.jsx
- src/pages/ResetPassword.jsx
- src/styles/customElementStyle.js
- src/styles/customLayoutStyle.js
- src/styles/theme.js
**PR** : 
-  커뮤니티 페이지 Styled Component Theme + REM unit 적용
- #182 
-
> Style 커뮤니티 페이지 CSS theme 적용

- src/components/elements/modal/ToastMessage.jsx
- src/components/recipeMain/AllRecipeList.jsx
- src/styles/GlobalStyle.jsx
- src/styles/customFormStyle.js
- src/styles/customLayoutStyle.js
> style 커뮤니티 페이지 반응형 마무리

- src/components/elements/button/NavButtonGoBack.jsx
- src/components/elements/button/NavButtonGoMain.jsx
- src/components/recipeCreate/RecipeCreateNavigation.jsx
- src/pages/NotFound.jsx
- src/partial/Footer.jsx
- src/partial/Navigation.jsx
- src/styles/theme.js
**PR** : 
- location state 초기화
- #235
> Bugfix location state 초기화

- src/components/elements/button/NavButtonGoBack.jsx
- src/components/elements/button/NavButtonGoMain.jsx
- src/partial/Footer.jsx
- src/partial/Navigation.jsx
**PR** : 
-  location에 state: undefined도 추가
- #235
> Bugfix location에 state: undefined도 추가

- src/components/recipeCreate/RecipeCreateNavigation.jsx
- src/components/recipeCreate/RecipeCreateWrap.jsx
- src/components/recipeCreate/element/RecipeCreateIngredient.jsx
- src/components/recipeCreate/element/RecipeCreateModal.jsx
- src/components/recipeCreate/element/RecipeIngredient.jsx
- src/components/recipeCreate/element/RecipeIngredientColorList.jsx
- src/components/recipeCreate/element/RecipeIngredientNumber.jsx
- src/components/recipeCreate/element/RecipeInput.jsx
- src/components/recipeCreate/subpages/RecipeIngredientButtonContainer.jsx
- src/components/recipeCreate/subpages/RecipeIngredientForm.jsx
- src/components/recipeDetail/IngredientsContainer.jsx
- src/components/recipeDetail/element/Ingredient.jsx
- src/pages/Recipe.jsx
- src/util/recipeCreate/recipeIngredientAmount.js
- src/util/recipeIngrediantColorList.js
- vite.config.js
**PR** : 
- 레시피 작성 UI 변경 및 재료 영역 깨짐 수정
> Update 레시피 작성 UI 변경 및 재료 영역 깨짐 수정

- .github/workflows/main.yml
- src/components/recipeCreate/RecipeCreateNavigation.jsx
- src/components/recipeCreate/RecipeCreateWrap.jsx
- src/components/recipeCreate/element/RecipeCreateIngredient.jsx
- src/components/recipeCreate/element/RecipeCreateModal.jsx
- src/components/recipeCreate/element/RecipeIngredient.jsx
- src/components/recipeCreate/element/RecipeIngredientColorList.jsx
- src/components/recipeCreate/element/RecipeIngredientNumber.jsx
- src/components/recipeCreate/element/RecipeInput.jsx
- src/components/recipeCreate/subpages/RecipeIngredientButtonContainer.jsx
- src/components/recipeCreate/subpages/RecipeIngredientForm.jsx
- src/components/recipeDetail/IngredientsContainer.jsx
- src/components/recipeDetail/element/Ingredient.jsx
- src/pages/Recipe.jsx
- src/util/recipeCreate/recipeIngredientAmount.js
- src/util/recipeIngrediantColorList.js
**PR** : 
- Update main.yml 수정 및 레시피 작성 UI 변경
> Update 레시피 작성 UI 수정

- src/components/recipeCreate/RecipeCreateNavigation.jsx
- src/components/recipeCreate/RecipeCreateWrap.jsx
- src/components/recipeCreate/element/RecipeCreateIngredient.jsx
- src/components/recipeCreate/element/RecipeCreateModal.jsx
- src/components/recipeCreate/element/RecipeIngredient.jsx
- src/components/recipeCreate/element/RecipeIngredientColorList.jsx
- src/components/recipeCreate/element/RecipeIngredientNumber.jsx
- src/components/recipeCreate/element/RecipeInput.jsx
- src/components/recipeCreate/subpages/RecipeIngredientButtonContainer.jsx
- src/components/recipeCreate/subpages/RecipeIngredientForm.jsx
- src/components/recipeDetail/IngredientsContainer.jsx
- src/components/recipeDetail/element/Ingredient.jsx
- src/pages/Recipe.jsx
- src/server/server.axios.js
- src/styles/theme.js
- src/util/recipeCreate/recipeIngredientAmount.js
- src/util/recipeIngrediantColorList.js
- vite.config.js
**PR** : 
- 브레이크 포인트 수정 425px => 320px
> Update 브레이크 포인트 수정

- src/components/recipeMain/AllRecipeList.jsx
- src/util/recipeCreate/recipeIngredientAmount.js
**PR** : 
- 커뮤니티 페이지 무한스크롤 중복 수정
- get요청 page에 +1 추가
> bugfix 커뮤니티 페이지 무한스크롤 중복 수정

- src/components/recipeComment/CommentInput.jsx
**PR** : 
- 코멘트 작성 시간 9시간 전 수정
- 함수 추가
- #235
> Bugfix 코멘트 작성 시간 9시간 전 수정

- src/components/recipeComment/CommentInput.jsx
- src/pages/Recipe.jsx
**PR** : 
- 댓글 바로 보이게 다시 수정
- setState를 빠트려서 다시 추가하였습니다.
> Bugfix 댓글 바로 보이게 다시 수정

- src/components/elements/modal/ToastMessage.jsx
- src/components/recipeComment/CommentBody.jsx
- src/components/recipeComment/CommentInput.jsx
- src/components/recipeDetail/element/RecipeDescBody.jsx
- src/components/register/Image.jsx
- src/pages/Mypage.jsx
- src/styles/GlobalStyle.jsx
- src/styles/customReset.css
**PR** : 
- rem관련 깨짐 수정, 리사이즈url 적용진행 중
- #254
> Bugfix rem관련 깨짐 수정, 리사이즈url 적용진행 중

- src/assets/manifest.json
**PR** : 
- Update manifest.json url에 /추가
```
"start_url": "https://cupick.co/",
```
> Update manifest.json url에 /추가

- src/assets/manifest.json
**PR** : 
- 버그 해결 중
- img url 경로 수정
> Bugfix 아이콘 img url 경로 수정

- src/assets/manifest.json
**PR** : 
- manifest.json url
- relative src
> Bugfix manifest.json url

- src/assets/manifest.json
**PR** : 
- manifest.json src 경로 수정
> Bugfix manifest.json src 경로 수정

- src/pages/Error.jsx
- src/pages/RecipeDetail.jsx
- src/partial/Navigation.jsx
- src/shared/Router.jsx
- src/styles/customLayoutStyle.js
- src/styles/customReset.css
**PR** : 
- CSS theme & 임시 serverDown코드
- 내일 아침까지 서버 작업
- serverDown
```jsx
/*** 서버 다운 ***/
const [serverDown, setServerDown] = useState(true);
if (serverDown) {
return (
<Routes>
<Route path="*" element={<Error />} />
</Routes>
);
}
```
> Update CSS theme & 임시 serverDown코드

- src/shared/Router.jsx
> Update 서버 정비 끝

- src/common/Layout.jsx
- src/components/recipeComment/CommentBody.jsx
- src/components/recipeComment/CommentInput.jsx
- src/pages/Comments.jsx
- src/pages/Mypage.jsx
- src/styles/customElementStyle.js
- src/styles/customLayoutStyle.js
- src/styles/customReset.css
**PR** : 
- 댓글 페이지 px rem으로 교체
> Style 댓글 페이지 px rem으로 교체

- src/common/Layout.jsx
- src/components/recipeComment/CommentEdit.jsx
- src/components/recipeComment/CommentInput.jsx
- src/components/recipeCreate/RecipeCreateWrap.jsx
- src/components/recipeCreate/RecipeFormContainer.jsx
- src/components/recipeCreate/RecipeVisualContainer.jsx
- src/components/recipeCreate/element/RecipeCreateIngredient.jsx
- src/components/recipeCreate/element/RecipeCreateModal.jsx
- src/components/recipeCreate/element/RecipeIngredient.jsx
- src/components/recipeCreate/subpages/RecipeCreateIngredientsContainer.jsx
- src/components/recipeCreate/subpages/RecipeCupSize.jsx
- src/components/recipeCreate/subpages/RecipeIngredientButtonContainer.jsx
- src/components/recipeCreate/subpages/RecipeIngredientConform.jsx
- src/components/recipeCreate/subpages/RecipeIsIced.jsx
- src/pages/Mypage.jsx
- src/styles/customLayoutStyle.js
- vite.config.js
**PR** : 
- 레이아웃 중앙 정렬, 레시피 성 페이지 버그, 등
- #287
> Bugfix 레이아웃 중앙 정렬, 레시피 성 페이지 버그, 등

- index.html
- src/components/recipeMain/AllRecipeList.jsx
- src/components/recipeMain/AllRecipeListContainer.jsx
- src/components/recipeMain/RecipeBody.jsx
- src/components/recipeMain/RecipeListContainer.jsx
- src/shared/Router.jsx
**PR** : 
- lighthouse performance score 향상
> Upgrade Lighthouse Score

- index.html
- pwa/manifest.json
**PR** : 
- bugfix pwa start_url
```
pwa\manifest.json
```
> bugfix pwa start_url

- index.html
**PR** : 
- bugfix pwa image href
```
index.html
```
> bugfix pwa image href

- index.html
- manifest.json
**PR** : 
- bugfix pwa manifest
```
manifest.json
```
> bugfix pwa manifest

- index.html
**PR** : 
- bugfix pwa sw.js 경로 수정
```
index.html
```
> bugfix pwa sw.js 경로 수정

- src/components/recipeDetail/element/RecipeDescBody.jsx
**PR** : 
- Update 레시피상세 페이지 수정,삭제 버튼 추가
```
src\components\recipeDetail\element\RecipeDescBody.jsx
```
> Update 레시피상세 페이지 수정,삭제 버튼 추가

- src/styles/customReset.css
**PR** : 
- css none -> auto 수정
```
src\styles\customReset.css
```
> Bugfix css none -> auto 수정

- src/components/recipeComment/CommentEdit.jsx
**PR** : 
* Feature 커뮤니티 페이지에 탑버튼 추가
* Update NotFound 페이지에 img 기본 높이 추가
* Style 프로필 수정 페이지 CustomStyle적용
* Hotfix 댓글 수정 쪽 영역깨짐 고침
> Hotfix 댓글 수정 쪽 영역깨짐 고침 (#329)

- src/components/recipeCreate/RecipeCreateWrap.jsx
- src/components/recipeCreate/RecipeFormContainer.jsx
- src/components/recipeCreate/RecipeVisualContainer.jsx
- src/components/recipeCreate/subpages/RecipeIngredientForm.jsx
**PR** : 
- 레시피 작성 페이지 하단 모바일 비율 깨짐 수정
> Hotfix 레시피 작성 페이지 하단 모바일 비율 깨짐 수정

- src/components/recipeCreate/RecipeCreateWrap.jsx
- src/components/recipeCreate/RecipeFormContainer.jsx
- src/components/recipeCreate/RecipeVisualContainer.jsx
- src/components/recipeCreate/subpages/RecipeIngredientForm.jsx
**PR** : 
- 레시피 작성 페이지
- 재료 점선 영역 2px 줄임
> Hotfix 재료 점선 영역 2px 줄임

- src/components/profileEdit/ProfileEditHeader.jsx
- src/components/recipeComment/CommentInput.jsx
- src/components/recipeCreate/RecipeCreateWrap.jsx
- src/components/recipeCreate/RecipeFormContainer.jsx
- src/components/recipeCreate/RecipeVisualContainer.jsx
- src/components/recipeCreate/subpages/RecipeIngredientForm.jsx
- src/components/recipeMypage/MypageMyInfo.jsx
- src/styles/GlobalStyle.jsx
**PR** : 
- Hotfix 댓글 확인 버튼 밀림 수정
> Hotfix 댓글 확인 버튼 밀림 수정

- src/components/recipeMain/AllRecipeListContainer.jsx
- vite.config.js
**PR** : 
- 커뮤니티 페이지 좋아요 버튼 버그 수정
- #342 
```
- src\components\recipeMain\AllRecipeListContainer.jsx
```
> Bugfix 커뮤니티 페이지 좋아요 버튼 버그 수정

- src/components/recipeMain/AllRecipeList.jsx
- src/components/recipeMain/AllRecipeListContainer.jsx
- src/components/userGuide/UserGuideContents.jsx
**PR** : 
- #350 비로그인시 레시피 작성 경로 수정
- 좋아요 기능  비로그인시 토스트모달 -> 컨펌모달로 교체
```
src\components\userGuide\UserGuideContents.jsx
src\components\recipeMain\AllRecipeList.jsx
src\components\recipeMain\AllRecipeListContainer.jsx
```
> Update 좋아요 기능 비로그인시 컨펌모달로 교체

- src/components/recipeComment/CommentEdit.jsx
- src/components/recipeComment/CommentInput.jsx
- src/components/recipeComment/CommentOption.jsx
- src/components/recipeCreate/element/RecipeInput.jsx
**PR** : 
- 댓글 수정할 때 프로필 이미지 src
- 토큰에서 imageUrl 삭제로 인해 해당 이미지 src수정
```jsx
<div className="input_profile">
<div className="profile_image">
{userLogin !== null && (
<StInputProfile
src={profiles?.imageUrl}
alt="유저 프로필 이미지"
></StInputProfile>
)}
</div>
</div>
```
> Bugfix 댓글 수정할 때 프로필 이미지 src

- src/components/recipeComment/CommentBody.jsx
- src/components/recipeComment/CommentEdit.jsx
- src/components/recipeComment/CommentInput.jsx
- src/components/recipeComment/CommentOption.jsx
- src/components/recipeCreate/element/RecipeInput.jsx
> Bugfix 댓글 IsNaN 수정

- src/components/recipeMain/RecipeBody.jsx
- src/components/recipeMain/element/RecipeSilder.jsx
> Hotfix 커뮤니티 페이지 가로 영역 수정

- src/components/recipeMain/RecipeBody.jsx
- src/components/recipeMain/element/RecipeSilder.jsx
- src/components/recipeMain/element/RecipeSlickBox.jsx
- src/components/recipeMain/element/RecipeTitle.jsx
- vite.config.js
**PR** : 
- 베스트레시피 댓글, 좋아요 기능 추가
- 베스트레시피 댓글, 좋아요 Count 숫자 추가
> Update 베스트레시피 디테일 기능 추가

- src/components/recipeDetail/IngredientsContainer.jsx
- src/components/recipeDetail/element/Ingredient.jsx
- src/components/recipeMain/RecipeBody.jsx
- src/components/recipeMain/element/RecipeSilder.jsx
- src/pages/Recipe.jsx
**PR** : 
- 레시피 상세페이지 재료 패딩  수정
> Hotfix 레시피 상세페이지 재료 패딩  수정

- src/components/recipeCreate/RecipeCreateNavigation.jsx
- src/components/recipeCreate/element/RecipeCreateIngredient.jsx
- src/components/recipeCreate/subpages/RecipeIngredientForm.jsx
- src/util/recipeCreate/recipeIngredientAmount.js
**PR** : 
- 레시피 작성 뒤로가기 버튼 수정
- #355
> Bugfix 레시피 작성 뒤로가기 버튼 수정

- src/components/userGuide/UserGuideContents.jsx
**PR** : 
- 레시피 메인 페이지에서 레시피 작성페이지로 가는 path 수정
```
src\components\userGuide\UserGuideContents.jsx
```
> Bugfix 레시피 작성페이지로 가는 path 수정

- src/partial/Footer.jsx
**PR** : 
- 비로그인 레시피 만들기 푸터 버튼 on
```
src/partial/Footer.jsx
```
> Hotfix 비로그인 레시피 만들기 푸터 버튼 on

- src/pages/ResetPassword.jsx
**PR** : 
- 존재하지 않는 이메일 문구 수정
- error메시지를 그대로 출력하면 문구가 잘리기 때문에 2줄로 나눠서 출력합니다.
- src/pages/ResetPassword.jsx
```jsx
setError("emailFailure", {
message: `${currentEmail}은(는)\n 존재하지 않는 이메일입니다.`,
});
```
> Update 존재하지 않는 이메일 문구 수정

- src/components/register/Nickname.jsx
- src/pages/ResetPassword.jsx
**PR** : 
- 회원가입 닉네임 유효성 텍스트 업데이트
> Update 회원가입 닉네임 유효성 텍스트

- src/components/recipeMain/RecipeBody.jsx
- src/components/register/Nickname.jsx
- src/pages/ResetPassword.jsx
**PR** : 
- 오후에 api 수정될 때까지 임시로 주석 처리합니다.
```
src\components\recipeMain\RecipeBody.jsx
```
> Update 베스트 레시피 임시 주석

- src/components/recipeMain/RecipeBody.jsx
- src/components/register/Nickname.jsx
- src/pages/ResetPassword.jsx
- src/server/server.axios.js
- src/shared/Router.jsx
**PR** : 
- Token 버그 관련 의존성 배열값 수정
- [loggedIn] => [pathname]
```
useEffect(() => {
// 리디렉션: 로그인 필요한 페이지에서 토큰이 만료 되었을 때 작동
if (pathNeedLoggedIn) {
if (!accessToken) {
navigate("/recipe");
}
if (loggedIn && !refreshToken) {
navigate("/sign-in", {
state: { message: "자동으로 \n 로그아웃 되었습니다." },
});
}
}
}, [pathname]);
```
> Bugfix Token 버그 관련 의존성 배열값 수정

- src/common/Layout.jsx
- src/pages/Badge.jsx
- src/pages/Bedge.jsx
- src/pages/Login.jsx
- src/shared/Router.jsx
- src/styles/customLayoutStyle.js
**PR** : 
- 뱃지 뷰 & 로그인 에러메시지 수정
- #391
> Feature 뱃지 뷰 & 로그인 에러메시지 수정

- src/pages/Register.jsx
- src/pages/ResetPassword.jsx
- vite.config.js
**PR** : 
- 회원가입과 비밀번호 초기화 관련 API 수정
```
```
> Hotfix 회원가입과 비밀번호 초기화 관련 API 수정

- src/common/Layout.jsx
- src/components/recipeMypage/MypageMyInfo.jsx
- src/pages/Badge.jsx
- src/pages/Login.jsx
- src/pages/Mypage.jsx
- src/pages/ProfileEdit.jsx
- src/pages/ResetPassword.jsx
- src/shared/Router.jsx
- vite.config.js
**PR** : 
- 비밀번호 리셋 페이지
- 사용자가 비밀번호 리셋 요청
- 요청 후 이메일에 있는 링크로 사이트에 접속 시, 
클라이언트에서 accessToken / refreshToken / resetPasswordToken 받아서 처리
- 사용자 자동 로그인 후, 프로필 수정 페이지로 랜딩
- #377
> Feature 비밀번호 리셋 후 자동 로그인

- src/common/Layout.jsx
- src/components/recipeMypage/MypageMyInfo.jsx
- src/pages/Badge.jsx
- src/pages/Login.jsx
- src/pages/Mypage.jsx
- src/pages/ProfileEdit.jsx
- src/pages/ResetPassword.jsx
- src/shared/Router.jsx
- vite.config.js
**PR** : 
- 비밀번호 리셋 페이지
- 사용자가 비밀번호 리셋 요청
- 요청 후 이메일에 있는 링크로 사이트에 접속 시, 
클라이언트에서 accessToken / refreshToken / resetPasswordToken 받아서 처리
- 사용자 자동 로그인 후, 프로필 수정 페이지로 랜딩
- #377
> Feature 비밀번호 리셋 후 자동 로그인 (#396)
